### PR TITLE
Fix Cypress `require.resolve` issue

### PR DESCRIPTION
**Pull request by samtsai**
## Description

Screenshot command fails when trying to read `package.json`. If bundler is loading via type `module` then `require.resolve` will fail and should fallback to hard-coded string path to `node_modules` like in `injectArgos`.

## Type of changes

`bug`

## Checklist

Valid all before asking for a code review to `argos-ci/code` :

- [x] I have read the CONTRIBUTING doc
- [x] The commits message follows the [Conventional Commits' policy](https://www.conventionalcommits.org/)
- [x] Lint and unit tests pass locally
- [n/a] I have added tests if needed

Optional checks:

- [n/a] My changes requires a change to the documentation
- [n/a] I have updated the documentation accordingly

### CODE REVIEW

**Comment by gregberge** [comment]
Thanks @samtsai, could you tell me how to reproduce this problem? Thanks.

**Comment by samtsai** [comment]
> Thanks @samtsai, could you tell me how to reproduce this problem? Thanks.

I've created a minimal repro branch:
https://github.com/samtsai/argos-javascript/tree/require-resolve-issue

I think I need to improve the solution to be similar to how you use `require.resolve` in other packages.

**Comment by gregberge** [comment]
@samtsai does it work with `createRequire`?

**Comment by samtsai** [comment]
@gregberge for my setup `createRequire` works yes. See latest changes in the PR.

**Review by gregberge — APPROVED** [review]

**Comment by gregberge** [comment]
> @gregberge for my setup `createRequire` works yes. See latest changes in the PR.

It didn't work, I just fallback to the path, no way to do a `require.resolve` with esbuild, so no choice here.

**Pull request merged**
