### PR TITLE
feat: get PR numbers

### LINKED ISSUE #40: Send pull-request number in @argos-ci/core
Send pull-request number to the server in `@argos-ci/core` package. It should be collected automatically from environment variables for all CI.

We will use `prNumber`.

### PR DESCRIPTION
**Pull request by jsfez**
Closes #40

### CODE REVIEW

**Review by gregberge — CHANGES_REQUESTED** [review]
We should support at least Travis and CircleCI.

**Review by gregberge — APPROVED** [review]
OK, let's store it in the backend before merging this!

**Review by gregberge — CHANGES_REQUESTED** [review]
@jsfez add the ability to override it using the CLI. Don't forget to document it.

**Comment by jsfez** [comment]
> @jsfez add the ability to override it using the CLI. Don't forget to document it.

I have added prNumber option to the CLI.

**Review by gregberge — APPROVED** [review]

**Pull request merged**
